dist: bionic

language: minimal

install:
  ## Update 'get.docksal.io' curl fails from time to time. Added '-k' to ignore cert error.
  ## ==> curl: (51) SSL: no alternative certificate subject name matches target host name 'get.docksal.io'
  - curl -kfsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo
  - env | grep SECRET_TERMINUS_TOKEN > .docksal/docksal-local.env
  - env | grep REMOTE_GIT_REPO >> .docksal/docksal-local.env
  - env | grep GH_TOKEN >> .docksal/docksal-local.env
  - cp .docksal/docksal-local.yml.sample .docksal/docksal-local.yml

before_script:
  - fin init
  #- fin cypress-install

script:
  ## NOTE: Travis cron only run once daily. To debug, temporarily add '--local' to 'fin drupal-coreupdate'.
  ##       Concatenating 3 commands below seems to fail silently since Drupal 8.9.6. Same issue with 8.9.7.
  #- fin drupal-coreupdate try
  #- fin test
  #- fin drupal-coreupdate sendpr
  - fail

after_success:
  # - fin deploy
  # testing:
  - fin storybook-deploy

notifications:
    on_success: always # default: change
    on_failure: always # default: always
