dist: bionic

language: minimal

install:
  ## Update 'get.docksal.io' curl fails from time to time. Added '-k' to ignore cert error.
  ## ==> curl: (51) SSL: no alternative certificate subject name matches target host name 'get.docksal.io'
  - curl -kfsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  ## NOTE: Travis cron only run once daily. To debug, temporarily add '--local' to 'fin drupal-coreupdate'.
  - fin drupal-coreupdate try --local
  - fin test
  - fin drupal-coreupdate sendpr --local

after_success:
  - fin deploy

notifications:
  email:
    recipients:
      - sysadmin@prometsource.com
      - aaron@prometsource.com
    on_success: always # default: change
    on_failure: always # default: always
  ## TODO: Need to encrypt the token as per https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
  ##       However, it's a minor security risk. It can always be done later.
  slack:
    rooms:
      - prometsourcegroup:gkT5UWM1XrtT8C10FKx1jNMB#provus
    on_success: always # default: change
    on_failure: always # default: always
