services:
  php:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: mysql
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        - echo "memory_limit = 2G" >> /usr/local/etc/php/conf.d/my-php.ini
      update:
        - composer self-update
        - composer install --optimize-autoloader
        - COMPOSER_ROOT_VERSION="${TUGBOAT_GITLAB_TARGET:-$TUGBOAT_PREVIEW}-dev" composer require drush/drush
        - mkdir -p "${DOCROOT}/sites/default/files"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;
        - ${TUGBOAT_ROOT}/vendor/bin/drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat --account-name=admin --account-pass=admin site:install provus provus_extension_configure_form.select_all='TRUE'
      build:
        - composer self-update
        - composer install --optimize-autoloader
        - COMPOSER_ROOT_VERSION="${TUGBOAT_GITLAB_TARGET:-$TUGBOAT_PREVIEW}-dev" composer require drush/drush
        - ${TUGBOAT_ROOT}/vendor/bin/drush updatedb -y
        - ${TUGBOAT_ROOT}/vendor/bin/drush cache:rebuild
  mysql:
    image: tugboatqa/mariadb:10